
// export const ADD_SELL_OFFER_BEGIN = 'ADD_SELL_OFFER_BEGIN';
// export const ADD_SELL_OFFER_SUCCESS = 'ADD_SELL_OFFER_SUCCESS';
// export const ADD_SELL_OFFER_FAILED = 'ADD_SELL_OFFER_FAILED';
// export const ADD_SELL_OFFER_INIT = 'ADD_SELL_OFFER_INIT';

export const AUTH_BEGIN = 'AUTH_BEGIN';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const CURRENT_STEP_NEXT = 'CURRENT_STEP_NEXT';

export const RESET_ACTIVE_CHANGE = 'RESET_ACTIVE_CHANGE';

export const EXIT_ACTIVE_CHANGE = 'EXIT_ACTIVE_CHANGE';

export const NONCE_FETCH = 'NONCE_FETCH';